#                                                                        #
# Settings Configuration for the Expose package                          #
#                                                                        #

TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'TYPO3.Neos.Expose': TRUE